-- Sports Booking System - Supabase PostgreSQL schema
-- How to run:
-- 1. Open Supabase Dashboard > SQL Editor > New query.
-- 2. Paste this whole file and click Run.
-- 3. Seed account password for all sample users is: 123456.
--    The database stores only bcrypt hashes generated by pgcrypto.
--
-- ===== QUY ƯỚC ID (varchar, prefix = viết tắt tên bảng) =====
-- users                  → u0001, u0002, ...
-- partner_profiles       → pp0001, pp0002, ...
-- court_categories       → cc0001, cc0002, ...
-- courts                 → c0001, c0002, ...
-- court_surfaces         → csf0001
-- court_images           → ci0001
-- court_amenities        → ca0001
-- court_prices           → cp0001
-- court_base_prices      → cbp0001
-- dynamic_pricing_rules  → dr0001
-- court_services         → cs0001
-- bookings               → b0001
-- demand_predictions     → dp0001
-- demand_features        → df0001
-- booking_services       → bs0001
-- reviews                → rv0001
-- reports                → rp0001
-- notifications          → nf0001
-- analytics_events       → ae0001
-- vouchers               → v0001
-- user_vouchers          → uv0001
-- booking_vouchers       → bv0001
-- blog_categories        → bc0001
-- blog_posts             → bp0001
-- blog_comments          → bco0001
-- blog_likes             → bl0001
-- tournaments            → tn0001
-- tournament_registrations → tr0001
-- team_recruitment_posts → tp0001
-- ================================================

create extension if not exists "pgcrypto";

-- ── DROP all ──────────────────────────────────────────────────────────
drop table if exists notifications cascade;
drop table if exists favorites cascade;
drop table if exists refresh_tokens cascade;
drop table if exists email_verification_codes cascade;
drop table if exists reports cascade;
drop table if exists analytics_events cascade;
drop table if exists demand_features cascade;
drop table if exists demand_predictions cascade;
drop table if exists dynamic_pricing_rules cascade;
drop table if exists court_base_prices cascade;
drop table if exists team_recruitment_posts cascade;
drop table if exists tournament_registrations cascade;
drop table if exists tournaments cascade;
drop table if exists blog_likes cascade;
drop table if exists blog_comments cascade;
drop table if exists blog_posts cascade;
drop table if exists blog_categories cascade;
drop table if exists booking_vouchers cascade;
drop table if exists payment_transactions cascade;
drop table if exists payments cascade;
drop table if exists booking_slots cascade;
drop table if exists user_vouchers cascade;
drop table if exists vouchers cascade;
drop table if exists reviews cascade;
drop table if exists booking_services cascade;
drop table if exists bookings cascade;
drop table if exists court_services cascade;
drop table if exists court_availability_blocks cascade;
drop table if exists court_prices cascade;
drop table if exists court_amenities cascade;
drop table if exists court_surfaces cascade;
drop table if exists court_images cascade;
drop table if exists courts cascade;
drop table if exists court_categories cascade;
drop table if exists partner_profiles cascade;
drop table if exists users cascade;

drop type if exists report_status cascade;
drop type if exists analytics_event_type cascade;
drop type if exists demand_prediction_status cascade;
drop type if exists demand_prediction_level cascade;
drop type if exists dynamic_pricing_rule_status cascade;
drop type if exists price_adjustment_type cascade;
drop type if exists dynamic_pricing_rule_type cascade;
drop type if exists team_recruitment_status cascade;
drop type if exists tournament_registration_status cascade;
drop type if exists tournament_status cascade;
drop type if exists blog_visibility cascade;
drop type if exists blog_post_status cascade;
drop type if exists user_voucher_status cascade;
drop type if exists voucher_status cascade;
drop type if exists voucher_discount_type cascade;
drop type if exists review_display_status cascade;
drop type if exists day_type cascade;
drop type if exists payment_method cascade;
drop type if exists payment_type cascade;
drop type if exists payment_status cascade;
drop type if exists booking_status cascade;
drop type if exists availability_block_status cascade;
drop type if exists court_active_status cascade;
drop type if exists approval_status cascade;
drop type if exists account_status cascade;
drop type if exists auth_provider cascade;
drop type if exists verification_purpose cascade;
drop type if exists user_role cascade;

-- Drop sequences
drop sequence if exists seq_users cascade;
drop sequence if exists seq_partner_profiles cascade;
drop sequence if exists seq_court_categories cascade;
drop sequence if exists seq_courts cascade;
drop sequence if exists seq_court_surfaces cascade;
drop sequence if exists seq_court_images cascade;
drop sequence if exists seq_court_amenities cascade;
drop sequence if exists seq_court_prices cascade;
drop sequence if exists seq_court_base_prices cascade;
drop sequence if exists seq_dynamic_pricing_rules cascade;
drop sequence if exists seq_court_services cascade;
drop sequence if exists seq_bookings cascade;
drop sequence if exists seq_demand_predictions cascade;
drop sequence if exists seq_demand_features cascade;
drop sequence if exists seq_booking_services cascade;
drop sequence if exists seq_reviews cascade;
drop sequence if exists seq_reports cascade;
drop sequence if exists seq_notifications cascade;
drop sequence if exists seq_analytics_events cascade;
drop sequence if exists seq_vouchers cascade;
drop sequence if exists seq_user_vouchers cascade;
drop sequence if exists seq_booking_vouchers cascade;
drop sequence if exists seq_blog_categories cascade;
drop sequence if exists seq_blog_posts cascade;
drop sequence if exists seq_blog_comments cascade;
drop sequence if exists seq_blog_likes cascade;
drop sequence if exists seq_tournaments cascade;
drop sequence if exists seq_tournament_registrations cascade;
drop sequence if exists seq_team_recruitment_posts cascade;

-- ── ENUM types ────────────────────────────────────────────────────────
create type user_role as enum ('USER', 'PARTNER', 'ADMIN');
create type auth_provider as enum ('LOCAL', 'GOOGLE');
create type verification_purpose as enum ('REGISTER', 'FORGOT_PASSWORD', 'CHANGE_EMAIL');
create type account_status as enum ('ACTIVE', 'LOCKED', 'INACTIVE', 'BLOCKED');
create type approval_status as enum ('PENDING', 'APPROVED', 'REJECTED');
create type court_active_status as enum ('ACTIVE', 'INACTIVE');
create type availability_block_status as enum ('ACTIVE', 'INACTIVE');
create type booking_status as enum ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW');
create type payment_status as enum ('UNPAID', 'PAID', 'PARTIALLY_REFUNDED', 'REFUNDED');
create type payment_method as enum ('CASH', 'QR_TRANSFER', 'BANK_TRANSFER', 'E_WALLET', 'ONLINE_GATEWAY');
create type payment_type as enum ('DEPOSIT', 'FULL_PAYMENT', 'REMAINING_PAYMENT');
create type day_type as enum ('WEEKDAY', 'WEEKEND', 'HOLIDAY');
create type review_display_status as enum ('VISIBLE', 'HIDDEN');
create type report_status as enum ('PENDING', 'RESOLVED', 'REJECTED');
create type dynamic_pricing_rule_type as enum ('PEAK_HOUR', 'OFF_PEAK_HOUR', 'WEEKEND', 'HOLIDAY', 'HIGH_DEMAND', 'LOW_DEMAND', 'CUSTOM');
create type price_adjustment_type as enum ('PERCENTAGE', 'FIXED_AMOUNT');
create type dynamic_pricing_rule_status as enum ('ACTIVE', 'INACTIVE');
create type demand_prediction_level as enum ('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH');
create type demand_prediction_status as enum ('GENERATED', 'INSUFFICIENT_DATA', 'FAILED');
create type analytics_event_type as enum (
  'COURT_VIEWED',
  'COURT_SEARCHED',
  'BOOKING_CREATED',
  'BOOKING_CANCELLED',
  'VOUCHER_CLAIMED',
  'VOUCHER_APPLIED',
  'TOURNAMENT_VIEWED',
  'TOURNAMENT_REGISTERED',
  'DYNAMIC_PRICE_VIEWED',
  'DYNAMIC_PRICE_CALCULATED',
  'PREDICTION_VIEWED',
  'DEMAND_PREDICTION_GENERATED',
  'TOURNAMENT_CREATED'
);
create type team_recruitment_status as enum ('OPEN', 'FULL', 'CLOSED', 'EXPIRED');
create type voucher_discount_type as enum ('PERCENTAGE', 'FIXED_AMOUNT');
create type voucher_status as enum ('DRAFT', 'ACTIVE', 'EXPIRED', 'DISABLED');
create type user_voucher_status as enum ('CLAIMED', 'USED', 'EXPIRED');
create type blog_post_status as enum ('DRAFT', 'PENDING', 'PUBLISHED', 'REJECTED', 'HIDDEN');
create type blog_visibility as enum ('PUBLIC', 'PRIVATE');
create type tournament_status as enum ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'OPEN', 'CLOSED', 'COMPLETED', 'CANCELLED');
create type tournament_registration_status as enum ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');

-- ── Sequences cho auto-generate ID ────────────────────────────────────
create sequence seq_users;
create sequence seq_partner_profiles;
create sequence seq_court_categories;
create sequence seq_courts;
create sequence seq_court_surfaces;
create sequence seq_court_images;
create sequence seq_court_amenities;
create sequence seq_court_prices;
create sequence seq_court_base_prices;
create sequence seq_dynamic_pricing_rules;
create sequence seq_court_services;
create sequence seq_bookings;
create sequence seq_demand_predictions;
create sequence seq_demand_features;
create sequence seq_booking_services;
create sequence seq_reviews;
create sequence seq_reports;
create sequence seq_notifications;
create sequence seq_analytics_events;
create sequence seq_vouchers;
create sequence seq_user_vouchers;
create sequence seq_booking_vouchers;
create sequence seq_blog_categories;
create sequence seq_blog_posts;
create sequence seq_blog_comments;
create sequence seq_blog_likes;
create sequence seq_tournaments;
create sequence seq_tournament_registrations;
create sequence seq_team_recruitment_posts;

-- ══════════════════════════════════════════════════════════════════════
-- TABLES
-- ══════════════════════════════════════════════════════════════════════

create table users (
  id varchar(20) primary key default ('u' || lpad(nextval('seq_users')::text, 4, '0')),
  full_name varchar(120) not null,
  email varchar(160) not null unique,
  phone varchar(30),
  password_hash text,
  role user_role not null default 'USER',
  provider auth_provider not null default 'LOCAL',
  provider_id varchar(160),
  email_verified boolean not null default false,
  avatar_url text,
  status account_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table refresh_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id varchar(20) not null references users(id) on delete cascade,
  token_hash text not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table email_verification_codes (
  id uuid primary key default gen_random_uuid(),
  email varchar(160) not null,
  full_name varchar(120) not null,
  phone varchar(30),
  password_hash text not null,
  otp_hash text not null,
  purpose verification_purpose not null default 'REGISTER',
  expires_at timestamptz not null,
  verified_at timestamptz,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 5 check (max_attempts > 0),
  resend_count integer not null default 0 check (resend_count >= 0),
  last_sent_at timestamptz not null default now(),
  account_type varchar(20) not null default 'USER',
  business_name varchar(180),
  address text,
  verification_document_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_email_verification_codes_email_purpose unique (email, purpose)
);

create index if not exists idx_email_verification_codes_expires_at
  on email_verification_codes(expires_at);

create table partner_profiles (
  id varchar(20) primary key default ('pp' || lpad(nextval('seq_partner_profiles')::text, 4, '0')),
  user_id varchar(20) not null unique references users(id) on delete cascade,
  business_name varchar(180) not null,
  address text not null,
  verification_document_url text,
  approval_status approval_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table court_categories (
  id varchar(20) primary key default ('cc' || lpad(nextval('seq_court_categories')::text, 4, '0')),
  name varchar(100) not null unique,
  slug varchar(120) not null unique,
  description text,
  status court_active_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table courts (
  id varchar(20) primary key default ('c' || lpad(nextval('seq_courts')::text, 4, '0')),
  partner_id varchar(20) not null references partner_profiles(id) on delete cascade,
  category_id varchar(20) not null references court_categories(id),
  name varchar(180) not null,
  slug varchar(200) not null unique,
  description text,
  address text not null,
  city varchar(80) not null,
  district varchar(80) not null,
  ward varchar(80),
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  opening_time time not null,
  closing_time time not null,
  map_url text,
  contact_phone varchar(30),
  contact_email varchar(160),
  facebook_url text,
  source_url text,
  verified boolean not null default false,
  court_count integer not null default 1 check (court_count > 0),
  price_note varchar(120),
  golden_price_note varchar(120),
  article_content text,
  directions text,
  surface_info text,
  approval_status approval_status not null default 'PENDING',
  active_status court_active_status not null default 'ACTIVE',
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint courts_opening_before_closing check (opening_time < closing_time)
);

create table court_surfaces (
  id varchar(20) primary key default ('csf' || lpad(nextval('seq_court_surfaces')::text, 4, '0')),
  court_id varchar(20) not null references courts(id) on delete cascade,
  code varchar(40) not null,
  name varchar(160) not null,
  capacity varchar(80),
  surface varchar(120),
  size varchar(120),
  image_url text,
  status court_active_status not null default 'ACTIVE',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table court_images (
  id varchar(20) primary key default ('ci' || lpad(nextval('seq_court_images')::text, 4, '0')),
  court_id varchar(20) not null references courts(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table court_amenities (
  id varchar(20) primary key default ('ca' || lpad(nextval('seq_court_amenities')::text, 4, '0')),
  court_id varchar(20) not null references courts(id) on delete cascade,
  name varchar(120) not null,
  created_at timestamptz not null default now()
);

create table court_prices (
  id varchar(20) primary key default ('cp' || lpad(nextval('seq_court_prices')::text, 4, '0')),
  court_id varchar(20) not null references courts(id) on delete cascade,
  day_type day_type not null,
  start_time time not null,
  end_time time not null,
  price numeric(12, 2) not null check (price >= 0),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint court_prices_time_check check (start_time < end_time)
);

create table court_base_prices (
  id varchar(20) primary key default ('cbp' || lpad(nextval('seq_court_base_prices')::text, 4, '0')),
  court_id varchar(20) not null references courts(id) on delete cascade,
  day_type day_type not null,
  start_time time not null,
  end_time time not null,
  base_price numeric(12, 2) not null check (base_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint court_base_prices_time_check check (start_time < end_time)
);

create table dynamic_pricing_rules (
  id varchar(20) primary key default ('dr' || lpad(nextval('seq_dynamic_pricing_rules')::text, 4, '0')),
  partner_id varchar(20) not null references partner_profiles(id) on delete cascade,
  court_id varchar(20) not null references courts(id) on delete cascade,
  name varchar(160) not null,
  description text,
  rule_type dynamic_pricing_rule_type not null,
  day_type day_type,
  start_time time,
  end_time time,
  price_adjustment_type price_adjustment_type not null,
  price_adjustment_value numeric(12, 2) not null,
  min_price numeric(12, 2),
  max_price numeric(12, 2),
  priority integer not null default 100,
  status dynamic_pricing_rule_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dynamic_pricing_rules_time_check check (start_time is null or end_time is null or start_time < end_time),
  constraint dynamic_pricing_rules_adjustment_check check (price_adjustment_value >= 0),
  constraint dynamic_pricing_rules_bounds_check check (min_price is null or max_price is null or min_price <= max_price)
);

create table court_services (
  id varchar(20) primary key default ('cs' || lpad(nextval('seq_court_services')::text, 4, '0')),
  court_id varchar(20) not null references courts(id) on delete cascade,
  name varchar(120) not null,
  description text,
  price numeric(12, 2) not null check (price >= 0),
  status court_active_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table court_availability_blocks (
  id uuid primary key default gen_random_uuid(),
  court_id varchar(20) not null references courts(id) on delete cascade,
  block_date date not null,
  start_time time not null,
  end_time time not null,
  reason text,
  status availability_block_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint court_availability_blocks_time_check check (start_time < end_time)
);

create table bookings (
  id varchar(20) primary key default ('b' || lpad(nextval('seq_bookings')::text, 4, '0')),
  booking_code varchar(30) not null unique,
  user_id varchar(20) not null references users(id),
  court_id varchar(20) not null references courts(id),
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  total_price numeric(12, 2) not null check (total_price >= 0),
  base_price numeric(12, 2) not null default 0 check (base_price >= 0),
  dynamic_adjustment_amount numeric(12, 2) not null default 0,
  subtotal numeric(12, 2) not null default 0 check (subtotal >= 0),
  voucher_discount_amount numeric(12, 2) not null default 0 check (voucher_discount_amount >= 0),
  demand_prediction_snapshot jsonb,
  payment_method payment_method not null default 'CASH',
  payment_status payment_status not null default 'UNPAID',
  booking_status booking_status not null default 'PENDING',
  cancel_reason text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_time_check check (start_time < end_time)
);

create table booking_slots (
  id uuid primary key default gen_random_uuid(),
  booking_id varchar(20) not null references bookings(id) on delete cascade,
  court_id varchar(20) not null references courts(id) on delete cascade,
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  slot_price numeric(12, 2) not null check (slot_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_slots_time_check check (start_time < end_time)
);

create table payments (
  id uuid primary key default gen_random_uuid(),
  booking_id varchar(20) not null references bookings(id) on delete cascade,
  user_id varchar(20) not null references users(id) on delete cascade,
  provider varchar(60) not null,
  payment_method payment_method not null,
  payment_type payment_type not null,
  amount numeric(12, 2) not null check (amount >= 0),
  currency varchar(3) not null default 'VND',
  status payment_status not null default 'UNPAID',
  external_order_id varchar(80) not null unique,
  external_transaction_id varchar(120),
  qr_code_url text,
  qr_payload text,
  payment_reference varchar(80) not null,
  expires_at timestamptz not null,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table payment_transactions (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null references payments(id) on delete cascade,
  provider varchar(60) not null,
  provider_transaction_id varchar(120) not null,
  provider_status varchar(40) not null,
  amount numeric(12, 2) not null check (amount >= 0),
  raw_payload_json jsonb not null,
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  constraint uq_payment_transactions_provider_tx unique(provider, provider_transaction_id)
);

create table demand_predictions (
  id varchar(20) primary key default ('dp' || lpad(nextval('seq_demand_predictions')::text, 4, '0')),
  court_id varchar(20) not null references courts(id) on delete cascade,
  prediction_date date not null,
  start_time time not null,
  end_time time not null,
  predicted_demand_score numeric(5, 2),
  predicted_occupancy_rate numeric(5, 2),
  confidence_score numeric(5, 2) not null default 0,
  prediction_level demand_prediction_level,
  model_version varchar(80) not null default 'rule-based-v1',
  status demand_prediction_status not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint demand_predictions_time_check check (start_time < end_time),
  constraint demand_predictions_score_check check (predicted_demand_score is null or predicted_demand_score between 0 and 100),
  constraint demand_predictions_occupancy_check check (predicted_occupancy_rate is null or predicted_occupancy_rate between 0 and 1),
  constraint demand_predictions_confidence_check check (confidence_score between 0 and 1)
);

create table demand_features (
  id varchar(20) primary key default ('df' || lpad(nextval('seq_demand_features')::text, 4, '0')),
  court_id varchar(20) not null references courts(id) on delete cascade,
  feature_date date not null,
  hour_of_day integer not null check (hour_of_day between 0 and 23),
  day_of_week integer not null check (day_of_week between 0 and 6),
  is_weekend boolean not null default false,
  is_holiday boolean not null default false,
  sport_type varchar(80),
  booking_count integer not null default 0 check (booking_count >= 0),
  cancellation_count integer not null default 0 check (cancellation_count >= 0),
  voucher_usage_count integer not null default 0 check (voucher_usage_count >= 0),
  average_price numeric(12, 2) not null default 0 check (average_price >= 0),
  occupancy_rate numeric(5, 2) not null default 0 check (occupancy_rate between 0 and 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table booking_services (
  id varchar(20) primary key default ('bs' || lpad(nextval('seq_booking_services')::text, 4, '0')),
  booking_id varchar(20) not null references bookings(id) on delete cascade,
  service_id varchar(20) not null references court_services(id),
  quantity integer not null check (quantity > 0),
  price numeric(12, 2) not null check (price >= 0),
  created_at timestamptz not null default now()
);

create table reviews (
  id varchar(20) primary key default ('rv' || lpad(nextval('seq_reviews')::text, 4, '0')),
  user_id varchar(20) not null references users(id),
  court_id varchar(20) not null references courts(id),
  booking_id varchar(20) not null unique references bookings(id),
  rating integer not null check (rating between 1 and 5),
  comment text,
  display_status review_display_status not null default 'VISIBLE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table reports (
  id varchar(20) primary key default ('rp' || lpad(nextval('seq_reports')::text, 4, '0')),
  user_id varchar(20) not null references users(id),
  court_id varchar(20) not null references courts(id),
  reason varchar(160) not null,
  description text,
  status report_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table notifications (
  id varchar(20) primary key default ('nf' || lpad(nextval('seq_notifications')::text, 4, '0')),
  user_id varchar(20) not null references users(id) on delete cascade,
  title varchar(160) not null,
  content text not null,
  type varchar(80) not null,
  metadata_json jsonb,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table favorites (
  id uuid primary key default gen_random_uuid(),
  user_id varchar(20) not null references users(id) on delete cascade,
  court_id varchar(20) not null references courts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, court_id)
);

create table analytics_events (
  id varchar(20) primary key default ('ae' || lpad(nextval('seq_analytics_events')::text, 4, '0')),
  user_id varchar(20) references users(id) on delete set null,
  partner_id varchar(20) references partner_profiles(id) on delete set null,
  event_type analytics_event_type not null,
  entity_type varchar(80) not null,
  entity_id varchar(20),
  metadata_json jsonb,
  created_at timestamptz not null default now()
);

create table vouchers (
  id varchar(20) primary key default ('v' || lpad(nextval('seq_vouchers')::text, 4, '0')),
  partner_id varchar(20) not null references partner_profiles(id) on delete cascade,
  court_id varchar(20) references courts(id) on delete cascade,
  code varchar(40) not null unique,
  title varchar(160) not null,
  description text,
  discount_type voucher_discount_type not null,
  discount_value numeric(12, 2) not null check (discount_value > 0),
  max_discount_amount numeric(12, 2) check (max_discount_amount is null or max_discount_amount >= 0),
  min_booking_amount numeric(12, 2) not null default 0 check (min_booking_amount >= 0),
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  used_count integer not null default 0 check (used_count >= 0),
  click_count integer not null default 0 check (click_count >= 0),
  start_date timestamptz not null,
  end_date timestamptz not null,
  status voucher_status not null default 'DRAFT',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vouchers_valid_date_check check (start_date < end_date),
  constraint vouchers_usage_check check (usage_limit is null or used_count <= usage_limit)
);

create table user_vouchers (
  id varchar(20) primary key default ('uv' || lpad(nextval('seq_user_vouchers')::text, 4, '0')),
  user_id varchar(20) not null references users(id) on delete cascade,
  voucher_id varchar(20) not null references vouchers(id) on delete cascade,
  status user_voucher_status not null default 'CLAIMED',
  claimed_at timestamptz not null default now(),
  used_at timestamptz,
  unique(user_id, voucher_id)
);

create table booking_vouchers (
  id varchar(20) primary key default ('bv' || lpad(nextval('seq_booking_vouchers')::text, 4, '0')),
  booking_id varchar(20) not null unique references bookings(id) on delete cascade,
  voucher_id varchar(20) not null references vouchers(id),
  discount_amount numeric(12, 2) not null check (discount_amount >= 0),
  created_at timestamptz not null default now()
);

create table blog_categories (
  id varchar(20) primary key default ('bc' || lpad(nextval('seq_blog_categories')::text, 4, '0')),
  name varchar(120) not null unique,
  slug varchar(140) not null unique,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table blog_posts (
  id varchar(20) primary key default ('bp' || lpad(nextval('seq_blog_posts')::text, 4, '0')),
  author_id varchar(20) not null references users(id) on delete cascade,
  title varchar(220) not null,
  slug varchar(240) not null unique,
  excerpt text,
  content text not null,
  cover_image_url text,
  category_id varchar(20) references blog_categories(id),
  status blog_post_status not null default 'DRAFT',
  visibility blog_visibility not null default 'PUBLIC',
  view_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create table blog_comments (
  id varchar(20) primary key default ('bco' || lpad(nextval('seq_blog_comments')::text, 4, '0')),
  post_id varchar(20) not null references blog_posts(id) on delete cascade,
  user_id varchar(20) not null references users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table blog_likes (
  id varchar(20) primary key default ('bl' || lpad(nextval('seq_blog_likes')::text, 4, '0')),
  post_id varchar(20) not null references blog_posts(id) on delete cascade,
  user_id varchar(20) not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(post_id, user_id)
);

create table tournaments (
  id varchar(20) primary key default ('tn' || lpad(nextval('seq_tournaments')::text, 4, '0')),
  partner_id varchar(20) not null references partner_profiles(id) on delete cascade,
  court_id varchar(20) not null references courts(id) on delete cascade,
  title varchar(220) not null,
  slug varchar(240) not null unique,
  description text,
  sport_type varchar(80) not null,
  cover_image_url text,
  start_date timestamptz not null,
  end_date timestamptz not null,
  registration_deadline timestamptz not null,
  max_participants integer not null check (max_participants > 0),
  current_participants integer not null default 0 check (current_participants >= 0),
  entry_fee numeric(12, 2) not null default 0 check (entry_fee >= 0),
  prize_description text,
  status tournament_status not null default 'DRAFT',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tournaments_date_check check (registration_deadline <= start_date and start_date <= end_date),
  constraint tournaments_capacity_check check (current_participants <= max_participants)
);

create table tournament_registrations (
  id varchar(20) primary key default ('tr' || lpad(nextval('seq_tournament_registrations')::text, 4, '0')),
  tournament_id varchar(20) not null references tournaments(id) on delete cascade,
  user_id varchar(20) not null references users(id) on delete cascade,
  team_name varchar(160),
  contact_phone varchar(30) not null,
  note text,
  status tournament_registration_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tournament_id, user_id)
);

create table team_recruitment_posts (
  id varchar(20) primary key default ('tp' || lpad(nextval('seq_team_recruitment_posts')::text, 4, '0')),
  user_id varchar(20) not null references users(id) on delete cascade,
  court_id varchar(20) references courts(id) on delete set null,
  title varchar(220) not null,
  sport_type varchar(80) not null,
  court_name varchar(180) not null,
  address text not null,
  current_players integer not null check (current_players >= 0),
  max_players integer not null check (max_players > 0),
  missing_players integer generated always as (greatest(max_players - current_players, 0)) stored,
  playing_date date,
  start_time time not null,
  end_time time not null,
  price_per_person numeric(12, 2) not null default 0 check (price_per_person >= 0),
  extra_services text,
  note text,
  zalo_group_link text,
  zalo_qr_image text,
  status team_recruitment_status not null default 'OPEN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_posts_time_check check (start_time < end_time),
  constraint team_posts_capacity_check check (current_players <= max_players)
);

-- ══════════════════════════════════════════════════════════════════════
-- TRIGGERS
-- ══════════════════════════════════════════════════════════════════════

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_users_updated_at before update on users for each row execute function set_updated_at();
create trigger trg_partner_profiles_updated_at before update on partner_profiles for each row execute function set_updated_at();
create trigger trg_court_categories_updated_at before update on court_categories for each row execute function set_updated_at();
create trigger trg_courts_updated_at before update on courts for each row execute function set_updated_at();
create trigger trg_court_prices_updated_at before update on court_prices for each row execute function set_updated_at();
create trigger trg_court_base_prices_updated_at before update on court_base_prices for each row execute function set_updated_at();
create trigger trg_dynamic_pricing_rules_updated_at before update on dynamic_pricing_rules for each row execute function set_updated_at();
create trigger trg_court_services_updated_at before update on court_services for each row execute function set_updated_at();
create trigger trg_court_availability_blocks_updated_at before update on court_availability_blocks for each row execute function set_updated_at();
create trigger trg_bookings_updated_at before update on bookings for each row execute function set_updated_at();
create trigger trg_booking_slots_updated_at before update on booking_slots for each row execute function set_updated_at();
create trigger trg_payments_updated_at before update on payments for each row execute function set_updated_at();
create trigger trg_reviews_updated_at before update on reviews for each row execute function set_updated_at();
create trigger trg_demand_predictions_updated_at before update on demand_predictions for each row execute function set_updated_at();
create trigger trg_demand_features_updated_at before update on demand_features for each row execute function set_updated_at();
create trigger trg_vouchers_updated_at before update on vouchers for each row execute function set_updated_at();
create trigger trg_blog_categories_updated_at before update on blog_categories for each row execute function set_updated_at();
create trigger trg_blog_posts_updated_at before update on blog_posts for each row execute function set_updated_at();
create trigger trg_blog_comments_updated_at before update on blog_comments for each row execute function set_updated_at();
create trigger trg_tournaments_updated_at before update on tournaments for each row execute function set_updated_at();
create trigger trg_tournament_registrations_updated_at before update on tournament_registrations for each row execute function set_updated_at();
create trigger trg_team_recruitment_posts_updated_at before update on team_recruitment_posts for each row execute function set_updated_at();

-- ══════════════════════════════════════════════════════════════════════
-- INDEXES
-- ══════════════════════════════════════════════════════════════════════

create index if not exists idx_users_email on users(email);
create index if not exists idx_users_provider_provider_id on users(provider, provider_id);
create index if not exists idx_users_role on users(role);
create index if not exists idx_users_status on users(status);
create index if not exists idx_refresh_tokens_user_id on refresh_tokens(user_id);
create index if not exists idx_refresh_tokens_token_hash on refresh_tokens(token_hash);
create index if not exists idx_partner_profiles_user_id on partner_profiles(user_id);
create index if not exists idx_partner_profiles_approval_status on partner_profiles(approval_status);
create index if not exists idx_courts_partner_id on courts(partner_id);
create index if not exists idx_courts_category_id on courts(category_id);
create index if not exists idx_courts_city on courts(city);
create index if not exists idx_courts_district on courts(district);
create index if not exists idx_courts_approval_status on courts(approval_status);
create index if not exists idx_courts_active_status on courts(active_status);
create index if not exists idx_courts_slug on courts(slug);
create index if not exists idx_court_surfaces_court_id on court_surfaces(court_id);
create index if not exists idx_court_base_prices_lookup on court_base_prices(court_id, day_type, start_time, end_time);
create index if not exists idx_court_availability_blocks_lookup on court_availability_blocks(court_id, block_date, start_time, end_time, status);
create index if not exists idx_dynamic_pricing_rules_lookup on dynamic_pricing_rules(court_id, status, priority);
create index if not exists idx_dynamic_pricing_rules_partner_id on dynamic_pricing_rules(partner_id);
create index if not exists idx_bookings_user_id on bookings(user_id);
create index if not exists idx_bookings_court_id on bookings(court_id);
create index if not exists idx_bookings_booking_date on bookings(booking_date);
create index if not exists idx_bookings_booking_status on bookings(booking_status);
create index if not exists idx_bookings_payment_status on bookings(payment_status);
create index if not exists idx_bookings_schedule_conflict on bookings(court_id, booking_date, start_time, end_time, booking_status);
create index if not exists idx_booking_slots_schedule on booking_slots(court_id, booking_date, start_time, end_time);
create index if not exists idx_booking_slots_booking_id on booking_slots(booking_id);
create index if not exists idx_payments_booking_id on payments(booking_id);
create index if not exists idx_payments_user_id on payments(user_id);
create index if not exists idx_payments_status_expires_at on payments(status, expires_at);
create index if not exists idx_payment_transactions_payment_id on payment_transactions(payment_id);
create index if not exists idx_reviews_court_id on reviews(court_id);
create index if not exists idx_reports_status on reports(status);
create index if not exists idx_notifications_user_read_created on notifications(user_id, is_read, created_at);
create index if not exists idx_favorites_user_id on favorites(user_id);
create index if not exists idx_favorites_court_id on favorites(court_id);
create index if not exists idx_demand_predictions_lookup on demand_predictions(court_id, prediction_date, start_time);
create index if not exists idx_demand_features_lookup on demand_features(court_id, feature_date, hour_of_day);
create index if not exists idx_analytics_events_lookup on analytics_events(event_type, entity_type, created_at);
create index if not exists idx_analytics_events_user_id on analytics_events(user_id);
create index if not exists idx_analytics_events_partner_id on analytics_events(partner_id);
create index if not exists idx_vouchers_partner_id on vouchers(partner_id);
create index if not exists idx_vouchers_court_id on vouchers(court_id);
create index if not exists idx_vouchers_code on vouchers(code);
create index if not exists idx_vouchers_status on vouchers(status);
create index if not exists idx_vouchers_partner_court_status on vouchers(partner_id, court_id, status);
create index if not exists idx_vouchers_date_range on vouchers(start_date, end_date);
create index if not exists idx_user_vouchers_user_id on user_vouchers(user_id);
create index if not exists idx_user_vouchers_voucher_id on user_vouchers(voucher_id);
create index if not exists idx_booking_vouchers_booking_id on booking_vouchers(booking_id);
create index if not exists idx_blog_posts_author_id on blog_posts(author_id);
create index if not exists idx_blog_posts_status on blog_posts(status);
create index if not exists idx_blog_posts_slug on blog_posts(slug);
create index if not exists idx_blog_comments_post_id on blog_comments(post_id);
create index if not exists idx_tournaments_partner_id on tournaments(partner_id);
create index if not exists idx_tournaments_court_id on tournaments(court_id);
create index if not exists idx_tournaments_status on tournaments(status);
create index if not exists idx_tournaments_slug on tournaments(slug);
create index if not exists idx_tournaments_partner_court_status on tournaments(partner_id, court_id, status);
create index if not exists idx_tournament_registrations_tournament_id on tournament_registrations(tournament_id);
create index if not exists idx_tournament_registrations_user_id on tournament_registrations(user_id);
create index if not exists idx_team_posts_status on team_recruitment_posts(status);
create index if not exists idx_team_posts_sport_type on team_recruitment_posts(sport_type);
create index if not exists idx_team_posts_playing_date on team_recruitment_posts(playing_date);
create index if not exists idx_team_posts_user_id on team_recruitment_posts(user_id);
