-- Reset the four documented demo accounts to their original password.
-- PostgreSQL stores only bcrypt hashes generated by pgcrypto.
create extension if not exists pgcrypto;

update users
set password_hash = crypt('123456', gen_salt('bf', 10)),
    provider = 'LOCAL',
    provider_id = null,
    email_verified = true,
    status = 'ACTIVE',
    updated_at = now()
where lower(email) in (
  'admin@sportsbooking.com',
  'partner1@sportsbooking.com',
  'partner2@sportsbooking.com',
  'user1@sportsbooking.com'
);
