-- Sports Booking System - Supabase PostgreSQL schema
-- How to run:
-- 1. Open Supabase Dashboard > SQL Editor > New query.
-- 2. Paste this whole file and click Run.
-- 3. Seed account password for all sample users is: 123456.
--    The database stores only bcrypt hashes generated by pgcrypto.

create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

drop table if exists notifications cascade;
drop table if exists reports cascade;
drop table if exists reviews cascade;
drop table if exists booking_services cascade;
drop table if exists bookings cascade;
drop table if exists court_services cascade;
drop table if exists court_prices cascade;
drop table if exists court_amenities cascade;
drop table if exists court_surfaces cascade;
drop table if exists court_images cascade;
drop table if exists courts cascade;
drop table if exists court_categories cascade;
drop table if exists partner_profiles cascade;
drop table if exists users cascade;

drop type if exists report_status cascade;
drop type if exists review_display_status cascade;
drop type if exists day_type cascade;
drop type if exists payment_method cascade;
drop type if exists payment_status cascade;
drop type if exists booking_status cascade;
drop type if exists court_active_status cascade;
drop type if exists approval_status cascade;
drop type if exists account_status cascade;
drop type if exists user_role cascade;

create type user_role as enum ('USER', 'PARTNER', 'ADMIN');
create type account_status as enum ('ACTIVE', 'LOCKED');
create type approval_status as enum ('PENDING', 'APPROVED', 'REJECTED');
create type court_active_status as enum ('ACTIVE', 'INACTIVE');
create type booking_status as enum ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW');
create type payment_status as enum ('UNPAID', 'PAID', 'REFUNDED');
create type payment_method as enum ('CASH', 'BANK_TRANSFER', 'E_WALLET', 'MOCK_PAYMENT');
create type day_type as enum ('WEEKDAY', 'WEEKEND', 'HOLIDAY');
create type review_display_status as enum ('VISIBLE', 'HIDDEN');
create type report_status as enum ('PENDING', 'RESOLVED', 'REJECTED');

create table users (
  id uuid primary key default uuid_generate_v4(),
  full_name varchar(120) not null,
  email varchar(160) not null unique,
  phone varchar(30),
  password_hash text not null,
  role user_role not null default 'USER',
  avatar_url text,
  status account_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table partner_profiles (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null unique references users(id) on delete cascade,
  business_name varchar(180) not null,
  address text not null,
  verification_document_url text,
  approval_status approval_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table court_categories (
  id uuid primary key default uuid_generate_v4(),
  name varchar(100) not null unique,
  slug varchar(120) not null unique,
  description text,
  status court_active_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table courts (
  id uuid primary key default uuid_generate_v4(),
  partner_id uuid not null references partner_profiles(id) on delete cascade,
  category_id uuid not null references court_categories(id),
  name varchar(180) not null,
  slug varchar(200) not null unique,
  description text,
  address text not null,
  city varchar(80) not null,
  district varchar(80) not null,
  ward varchar(80),
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  opening_time time not null,
  closing_time time not null,
  map_url text,
  contact_phone varchar(30),
  contact_email varchar(160),
  facebook_url text,
  source_url text,
  verified boolean not null default false,
  court_count integer not null default 1 check (court_count > 0),
  price_note varchar(120),
  golden_price_note varchar(120),
  article_content text,
  directions text,
  surface_info text,
  approval_status approval_status not null default 'PENDING',
  active_status court_active_status not null default 'ACTIVE',
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint courts_opening_before_closing check (opening_time < closing_time)
);

create table court_surfaces (
  id uuid primary key default uuid_generate_v4(),
  court_id uuid not null references courts(id) on delete cascade,
  code varchar(40) not null,
  name varchar(160) not null,
  capacity varchar(80),
  surface varchar(120),
  size varchar(120),
  image_url text,
  status court_active_status not null default 'ACTIVE',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table court_images (
  id uuid primary key default uuid_generate_v4(),
  court_id uuid not null references courts(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table court_amenities (
  id uuid primary key default uuid_generate_v4(),
  court_id uuid not null references courts(id) on delete cascade,
  name varchar(120) not null,
  created_at timestamptz not null default now()
);

create table court_prices (
  id uuid primary key default uuid_generate_v4(),
  court_id uuid not null references courts(id) on delete cascade,
  day_type day_type not null,
  start_time time not null,
  end_time time not null,
  price numeric(12, 2) not null check (price >= 0),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint court_prices_time_check check (start_time < end_time)
);

create table court_services (
  id uuid primary key default uuid_generate_v4(),
  court_id uuid not null references courts(id) on delete cascade,
  name varchar(120) not null,
  description text,
  price numeric(12, 2) not null check (price >= 0),
  status court_active_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table bookings (
  id uuid primary key default uuid_generate_v4(),
  booking_code varchar(30) not null unique,
  user_id uuid not null references users(id),
  court_id uuid not null references courts(id),
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  total_price numeric(12, 2) not null check (total_price >= 0),
  payment_method payment_method not null default 'CASH',
  payment_status payment_status not null default 'UNPAID',
  booking_status booking_status not null default 'PENDING',
  cancel_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_time_check check (start_time < end_time)
);

create table booking_services (
  id uuid primary key default uuid_generate_v4(),
  booking_id uuid not null references bookings(id) on delete cascade,
  service_id uuid not null references court_services(id),
  quantity integer not null check (quantity > 0),
  price numeric(12, 2) not null check (price >= 0),
  created_at timestamptz not null default now()
);

create table reviews (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references users(id),
  court_id uuid not null references courts(id),
  booking_id uuid not null unique references bookings(id),
  rating integer not null check (rating between 1 and 5),
  comment text,
  display_status review_display_status not null default 'VISIBLE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table reports (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references users(id),
  court_id uuid not null references courts(id),
  reason varchar(160) not null,
  description text,
  status report_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table notifications (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references users(id) on delete cascade,
  title varchar(160) not null,
  content text not null,
  type varchar(80) not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_users_updated_at before update on users for each row execute function set_updated_at();
create trigger trg_partner_profiles_updated_at before update on partner_profiles for each row execute function set_updated_at();
create trigger trg_court_categories_updated_at before update on court_categories for each row execute function set_updated_at();
create trigger trg_courts_updated_at before update on courts for each row execute function set_updated_at();
create trigger trg_court_prices_updated_at before update on court_prices for each row execute function set_updated_at();
create trigger trg_court_services_updated_at before update on court_services for each row execute function set_updated_at();
create trigger trg_bookings_updated_at before update on bookings for each row execute function set_updated_at();
create trigger trg_reviews_updated_at before update on reviews for each row execute function set_updated_at();

create index idx_users_email on users(email);
create index idx_users_role on users(role);
create index idx_users_status on users(status);
create index idx_partner_profiles_user_id on partner_profiles(user_id);
create index idx_partner_profiles_approval_status on partner_profiles(approval_status);
create index idx_courts_partner_id on courts(partner_id);
create index idx_courts_category_id on courts(category_id);
create index idx_courts_city on courts(city);
create index idx_courts_district on courts(district);
create index idx_courts_approval_status on courts(approval_status);
create index idx_courts_active_status on courts(active_status);
create index idx_courts_slug on courts(slug);
create index idx_court_surfaces_court_id on court_surfaces(court_id);
create index idx_bookings_user_id on bookings(user_id);
create index idx_bookings_court_id on bookings(court_id);
create index idx_bookings_booking_date on bookings(booking_date);
create index idx_bookings_booking_status on bookings(booking_status);
create index idx_bookings_payment_status on bookings(payment_status);
create index idx_bookings_schedule_conflict on bookings(court_id, booking_date, start_time, end_time, booking_status);
create index idx_reviews_court_id on reviews(court_id);
create index idx_reports_status on reports(status);
create index idx_notifications_user_id on notifications(user_id);

insert into users (id, full_name, email, phone, password_hash, role, status) values
('00000000-0000-0000-0000-000000000001', 'System Admin', 'admin@sportsbooking.com', '0900000001', crypt('123456', gen_salt('bf', 10)), 'ADMIN', 'ACTIVE'),
('00000000-0000-0000-0000-000000000011', 'Nguyen Van Partner 1', 'partner1@sportsbooking.com', '0900000011', crypt('123456', gen_salt('bf', 10)), 'PARTNER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000012', 'Tran Thi Partner 2', 'partner2@sportsbooking.com', '0900000012', crypt('123456', gen_salt('bf', 10)), 'PARTNER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000021', 'Le Minh Anh', 'user1@sportsbooking.com', '0900000021', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000022', 'Pham Gia Bao', 'user2@sportsbooking.com', '0900000022', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000023', 'Hoang Thu Ha', 'user3@sportsbooking.com', '0900000023', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000024', 'Do Quoc Huy', 'user4@sportsbooking.com', '0900000024', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000025', 'Bui Khanh Linh', 'user5@sportsbooking.com', '0900000025', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE');

insert into users (id, full_name, email, phone, password_hash, role, status) values
('00000000-0000-0000-0000-000000000013', 'Pham Quoc Partner 3', 'partner3@sportsbooking.com', '0900000013', crypt('123456', gen_salt('bf', 10)), 'PARTNER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000014', 'Le Minh Partner 4', 'partner4@sportsbooking.com', '0900000014', crypt('123456', gen_salt('bf', 10)), 'PARTNER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000015', 'Do Hanh Partner 5', 'partner5@sportsbooking.com', '0900000015', crypt('123456', gen_salt('bf', 10)), 'PARTNER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000026', 'Nguyen Quang Vinh', 'user6@sportsbooking.com', '0900000026', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000027', 'Tran Mai Phuong', 'user7@sportsbooking.com', '0900000027', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000028', 'Vo Thanh Long', 'user8@sportsbooking.com', '0900000028', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000029', 'Dang Thuy Duong', 'user9@sportsbooking.com', '0900000029', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000030', 'Ngo Bao Chau', 'user10@sportsbooking.com', '0900000030', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000031', 'Huynh Duc Anh', 'user11@sportsbooking.com', '0900000031', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE'),
('00000000-0000-0000-0000-000000000032', 'Mai Phuong Nam', 'user12@sportsbooking.com', '0900000032', crypt('123456', gen_salt('bf', 10)), 'USER', 'ACTIVE');

insert into partner_profiles (id, user_id, business_name, address, approval_status) values
('10000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000011', 'Sai Gon Sport Hub', '12 Nguyen Huu Canh, Binh Thanh, TP.HCM', 'APPROVED'),
('10000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000012', 'Ha Noi Active Courts', '88 Tran Duy Hung, Cau Giay, Ha Noi', 'APPROVED');

insert into partner_profiles (id, user_id, business_name, address, approval_status) values
('10000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000013', 'Green Field Sports', '45 Pham Van Dong, Go Vap, TP.HCM', 'APPROVED'),
('10000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000014', 'Da Nang Court Center', '12 Bach Dang, Hai Chau, Da Nang', 'APPROVED'),
('10000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000015', 'Mekong Sport Arena', '20 Nguyen Trai, Ninh Kieu, Can Tho', 'APPROVED');

insert into court_categories (id, name, slug, description) values
('20000000-0000-0000-0000-000000000001', 'Bong da mini', 'bong-da-mini', 'San bong da 5-7 nguoi'),
('20000000-0000-0000-0000-000000000002', 'Tennis', 'tennis', 'San tennis tieu chuan'),
('20000000-0000-0000-0000-000000000003', 'Bong chuyen', 'bong-chuyen', 'San bong chuyen trong nha va ngoai troi'),
('20000000-0000-0000-0000-000000000004', 'Cau long', 'cau-long', 'San cau long co tham va den'),
('20000000-0000-0000-0000-000000000005', 'Bong ro', 'bong-ro', 'San bong ro 3x3 va 5x5'),
('20000000-0000-0000-0000-000000000006', 'Pickleball', 'pickleball', 'San pickleball moi');

insert into courts (id, partner_id, category_id, name, slug, description, address, city, district, ward, latitude, longitude, opening_time, closing_time, map_url, contact_phone, contact_email, facebook_url, source_url, verified, court_count, price_note, golden_price_note, article_content, directions, surface_info, approval_status, active_status) values
('30000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000001','San bong Sala 1','san-bong-sala-1','San co nhan tao, den LED, gui xe mien phi.','10 Mai Chi Tho','TP.HCM','Thu Duc','An Phu',10.7749000,106.7573000,'06:00','23:00','https://maps.google.com','0900000011','partner1@sportsbooking.com','https://facebook.com','https://sportsbooking.local/courts/san-bong-sala-1',true,3,'Tu 120.000d/gio','Lien he gio vang','San bong Sala 1 co he thong den LED, mat co nhan tao va khu gui xe rong. San phu hop cho giao huu, tap luyen va to chuc giai nho.','Di theo Mai Chi Tho, vao khu do thi Sala va re phai tai cong san the thao.','Co nhan tao mem, bao duong dinh ky.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000002','10000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000002','Tennis Riverside','tennis-riverside','San tennis mat cung gan trung tam.','35 Nguyen Van Huong','TP.HCM','Thu Duc','Thao Dien',10.8035000,106.7333000,'05:30','22:00','https://maps.google.com','0900000011','partner1@sportsbooking.com','https://facebook.com',null,true,2,'Tu 180.000d/gio','Tu 250.000d/gio','Tennis Riverside co mat san phang, khong gian thoang va khu nghi cho nguoi choi.','Di theo Nguyen Van Huong, san nam ben phai gan khu dan cu Thao Dien.','Mat san tennis acrylic.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000003','10000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000004','Cau long Phu Nhuan','cau-long-phu-nhuan','San cau long trong nha, mat san tot.','22 Phan Dang Luu','TP.HCM','Phu Nhuan','Ward 3',10.8010000,106.6798000,'06:00','22:30',null,'0900000011',null,null,null,true,6,'Tu 120.000d/gio','Lien he',null,null,'Tham cau long PVC, den chieu sang trong nha.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000004','10000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000006','Pickleball Tan Binh','pickleball-tan-binh','Cum 4 san pickleball moi.','18 Cong Hoa','TP.HCM','Tan Binh','Ward 12',10.8017000,106.6522000,'06:00','22:00',null,'0900000011',null,null,null,true,4,'Tu 150.000d/gio','Tu 220.000d/gio',null,null,'Mat san pickleball ngoai troi.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000005','10000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000005','Basketball District 7','basketball-district-7','San bong ro ngoai troi co mai che.','99 Nguyen Thi Thap','TP.HCM','Quan 7','Tan Phu',10.7388000,106.7196000,'07:00','22:00',null,'0900000011',null,null,null,false,1,'Lien he','Lien he',null,null,null,'PENDING','ACTIVE'),
('30000000-0000-0000-0000-000000000006','10000000-0000-0000-0000-000000000002','20000000-0000-0000-0000-000000000001','San bong My Dinh','san-bong-my-dinh','San bong mini gan san van dong My Dinh.','1 Le Duc Tho','Ha Noi','Nam Tu Liem','My Dinh 1',21.0205000,105.7639000,'06:00','23:00','https://maps.google.com','0900000012','partner2@sportsbooking.com','https://facebook.com',null,true,3,'Tu 150.000d/gio','Lien he gio vang','San bong My Dinh phu hop cho cac doi bong phong trao va giai dau nho.','Di theo Le Duc Tho, gui xe tai cong phu.','Co nhan tao, den cao ap.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000007','10000000-0000-0000-0000-000000000002','20000000-0000-0000-0000-000000000002','Tennis Cau Giay','tennis-cau-giay','San tennis co huan luyen vien.','88 Tran Duy Hung','Ha Noi','Cau Giay','Trung Hoa',21.0092000,105.7967000,'05:30','22:00',null,'0900000012',null,null,null,true,2,'Tu 180.000d/gio','Tu 260.000d/gio',null,null,'Mat san acrylic.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000008','10000000-0000-0000-0000-000000000002','20000000-0000-0000-0000-000000000003','Bong chuyen Da Nang Center','bong-chuyen-da-nang-center','San bong chuyen thoang, gan bien.','45 Vo Nguyen Giap','Da Nang','Son Tra','Phuoc My',16.0678000,108.2440000,'06:00','21:30',null,'0900000012',null,null,null,true,2,'Tu 100.000d/gio','Lien he',null,null,null,'APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000009','10000000-0000-0000-0000-000000000002','20000000-0000-0000-0000-000000000004','Cau long Can Tho Arena','cau-long-can-tho-arena','Nha thi dau cau long tai Can Tho.','27 Hoa Binh','Can Tho','Ninh Kieu','Tan An',10.0342000,105.7842000,'06:00','22:00',null,'0900000012',null,null,null,true,8,'Tu 110.000d/gio','Lien he',null,null,null,'APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000010','10000000-0000-0000-0000-000000000002','20000000-0000-0000-0000-000000000006','Pickleball Binh Duong','pickleball-binh-duong','San pickleball cho nhom ban va gia dinh.','120 Binh Duong Boulevard','Binh Duong','Thu Dau Mot','Phu Hoa',10.9804000,106.6753000,'06:00','22:00',null,'0900000012',null,null,null,true,4,'Tu 150.000d/gio','Tu 220.000d/gio',null,null,null,'APPROVED','ACTIVE');

insert into courts (id, partner_id, category_id, name, slug, description, address, city, district, ward, latitude, longitude, opening_time, closing_time, map_url, contact_phone, contact_email, facebook_url, source_url, verified, court_count, price_note, golden_price_note, article_content, directions, surface_info, approval_status, active_status) values
('30000000-0000-0000-0000-000000000011','10000000-0000-0000-0000-000000000003','20000000-0000-0000-0000-000000000001','San bong The One Gamuda','san-bong-the-one-gamuda','Cum san bong da mini co nhan tao, co khu nghi cho doi bong.','Duong Gamuda Gardens','Ha Noi','Hoang Mai','Tran Phu',20.9813000,105.8769000,'05:30','23:00','https://maps.google.com','0900000013','partner3@sportsbooking.com','https://facebook.com','https://sportsbooking.local/courts/san-bong-the-one-gamuda',true,4,'Tu 250.000d/gio','Tu 350.000d/gio','San bong The One Gamuda nam trong khu do thi rong, phu hop da giao huu sau gio lam va to chuc giai phong trao. He thong den chieu sang du manh cho lich toi, co khu ve sinh va bai gui xe gan san.','Di vao cong Gamuda Gardens, chay thang theo truc chinh va re phai theo bien chi dan san bong.','Co nhan tao the he moi, mat san em va thoat nuoc tot.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000012','10000000-0000-0000-0000-000000000003','20000000-0000-0000-0000-000000000004','Cau long V-Slash Go Vap','cau-long-v-slash-go-vap','Nha thi dau cau long trong nha, co quat va khu cho.','62 Le Duc Tho','TP.HCM','Go Vap','Ward 15',10.8401000,106.6749000,'06:00','22:30','https://maps.google.com','0900000013','partner3@sportsbooking.com','https://facebook.com',null,true,10,'Tu 90.000d/gio','Tu 140.000d/gio','Cum san cau long V-Slash Go Vap co nhieu san trong nha, phu hop tap luyen ca nhan va nhom ban. San co khu giu xe va quay nuoc nho.','Tu Pham Van Dong re vao Le Duc Tho, san nam gan khu dan cu.','Tham PVC chong truot, vach san ro, den trong nha.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000013','10000000-0000-0000-0000-000000000003','20000000-0000-0000-0000-000000000002','Tennis Green Park','tennis-green-park','San tennis ngoai troi gan cong vien, co huan luyen vien theo gio.','18 Nguyen Thai Son','TP.HCM','Go Vap','Ward 3',10.8219000,106.6860000,'05:30','22:00','https://maps.google.com','0900000013',null,'https://facebook.com',null,true,3,'Tu 180.000d/gio','Tu 280.000d/gio','Tennis Green Park co mat san tot, khong gian thoang va dich vu thue vot.','Di theo Nguyen Thai Son, gui xe trong khu san.','Mat san acrylic, luoi va vach san bao duong dinh ky.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000014','10000000-0000-0000-0000-000000000004','20000000-0000-0000-0000-000000000005','Basketball Hai Chau Arena','basketball-hai-chau-arena','San bong ro trong nha co khan dai nho.','30 Nguyen Van Linh','Da Nang','Hai Chau','Nam Duong',16.0605000,108.2208000,'07:00','22:00','https://maps.google.com','0900000014','partner4@sportsbooking.com','https://facebook.com',null,true,2,'Tu 200.000d/gio','Tu 300.000d/gio','Basketball Hai Chau Arena phu hop cho cac tran 3x3, 5x5 va lop tap co ban.','Nam tren truc Nguyen Van Linh, de di tu trung tam thanh pho.','San go trong nha, bang ro tieu chuan.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000015','10000000-0000-0000-0000-000000000004','20000000-0000-0000-0000-000000000003','Bong chuyen My Khe Club','bong-chuyen-my-khe-club','San bong chuyen thoang, gan khu bien My Khe.','90 Vo Nguyen Giap','Da Nang','Son Tra','Phuoc My',16.0652000,108.2468000,'06:00','21:30','https://maps.google.com','0900000014',null,null,null,true,2,'Tu 120.000d/gio','Tu 180.000d/gio','Bong chuyen My Khe Club co mat san thoang, gan bien, phu hop cho nhom ban dat lich cuoi tuan.','Di doc Vo Nguyen Giap, san nam sau day nha dich vu.','Mat san tong hop ngoai troi.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000016','10000000-0000-0000-0000-000000000004','20000000-0000-0000-0000-000000000006','Pickleball Riverside Da Nang','pickleball-riverside-da-nang','Cum san pickleball moi gan song Han.','12 Tran Hung Dao','Da Nang','Son Tra','An Hai Bac',16.0732000,108.2309000,'06:00','22:00','https://maps.google.com','0900000014',null,'https://facebook.com',null,true,6,'Tu 160.000d/gio','Tu 240.000d/gio','Pickleball Riverside co vi tri gan song, mat san moi va khu nghi nho.','Nam tren Tran Hung Dao, gan cau Rong.','Mat san pickleball tieu chuan ngoai troi.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000017','10000000-0000-0000-0000-000000000005','20000000-0000-0000-0000-000000000001','San bong Ninh Kieu Star','san-bong-ninh-kieu-star','San bong da mini co nhan tao tai trung tam Can Tho.','15 Mau Than','Can Tho','Ninh Kieu','Xuan Khanh',10.0349000,105.7706000,'06:00','23:00','https://maps.google.com','0900000015','partner5@sportsbooking.com','https://facebook.com',null,true,3,'Tu 140.000d/gio','Tu 220.000d/gio','San bong Ninh Kieu Star nam gan khu sinh vien, lich toi soi dong va gia hop ly.','Tu Mau Than re vao hem lon, co bai xe may.','Co nhan tao, den LED.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000018','10000000-0000-0000-0000-000000000005','20000000-0000-0000-0000-000000000004','Cau long Mekong Hall','cau-long-mekong-hall','Nha cau long co nhieu san va khu thay do.','40 Nguyen Van Cu','Can Tho','Ninh Kieu','An Hoa',10.0457000,105.7665000,'05:30','22:30','https://maps.google.com','0900000015',null,null,null,true,8,'Tu 100.000d/gio','Tu 150.000d/gio','Cau long Mekong Hall co mat san tot, gio mo cua som va co dich vu thue vot.','Gan Nguyen Van Cu, thuan tien di tu trung tam Ninh Kieu.','Tham PVC trong nha.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000019','10000000-0000-0000-0000-000000000005','20000000-0000-0000-0000-000000000002','Tennis Tay Do','tennis-tay-do','San tennis yen tinh cho luyen tap ca nhan.','77 Nguyen Trai','Can Tho','Ninh Kieu','An Cu',10.0383000,105.7838000,'05:30','22:00','https://maps.google.com','0900000015',null,'https://facebook.com',null,true,2,'Tu 170.000d/gio','Tu 250.000d/gio','Tennis Tay Do phu hop cho nguoi choi moi va lop co huan luyen vien.','Nam gan trung tam, de tim bang Google Maps.','Mat san hard court.','APPROVED','ACTIVE'),
('30000000-0000-0000-0000-000000000020','10000000-0000-0000-0000-000000000003','20000000-0000-0000-0000-000000000006','Pickleball Phu Nhuan Plus','pickleball-phu-nhuan-plus','San pickleball gan trung tam, lich trong nhieu khung gio.','101 Hoang Van Thu','TP.HCM','Phu Nhuan','Ward 8',10.8012000,106.6684000,'06:00','22:00','https://maps.google.com','0900000013',null,null,null,true,4,'Tu 150.000d/gio','Tu 230.000d/gio','Pickleball Phu Nhuan Plus co vi tri thuan tien, phu hop dat san nhanh sau gio lam.','Nam gan cong vien Hoang Van Thu.','Mat san pickleball tieu chuan.','APPROVED','ACTIVE');

insert into court_surfaces (court_id, code, name, capacity, surface, size, image_url, sort_order)
select id, '01', name || ' 01', 'San 7', 'Co nhan tao', '55m x 35m', 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=500&q=80', 1 from courts union all
select id, '02', name || ' 02', 'San 7', 'Co nhan tao', '55m x 35m', 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=500&q=80', 2 from courts where court_count >= 2 union all
select id, '03', name || ' 03', 'San 11', 'Co nhan tao', '90m x 45m', 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=500&q=80', 3 from courts where court_count >= 3;

insert into court_images (court_id, image_url, sort_order)
select id, 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1200&q=80', 1 from courts;

insert into court_images (court_id, image_url, sort_order)
select id, 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80', 2 from courts union all
select id, 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=80', 3 from courts union all
select id, 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=1200&q=80', 4 from courts union all
select id, 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80', 5 from courts;

insert into court_amenities (court_id, name)
select id, unnest(array['Gui xe', 'Den chieu sang', 'Phong thay do']) from courts;

insert into court_amenities (court_id, name)
select id, unnest(array['Wifi', 'Nuoc uong', 'Khu nghi cho', 'Nha ve sinh', 'Bao ve', 'May ban nuoc']) from courts;

insert into court_prices (court_id, day_type, start_time, end_time, price, note)
select id, 'WEEKDAY'::day_type, '06:00'::time, '17:00'::time, 120000, 'Gio thap diem' from courts union all
select id, 'WEEKDAY'::day_type, '17:00'::time, '23:00'::time, 180000, 'Gio cao diem' from courts union all
select id, 'WEEKEND'::day_type, '06:00'::time, '23:00'::time, 220000, 'Cuoi tuan' from courts;

insert into court_prices (court_id, day_type, start_time, end_time, price, note)
select id, 'WEEKDAY'::day_type, '05:30'::time, '08:00'::time, 150000, 'Gio sang som' from courts union all
select id, 'WEEKDAY'::day_type, '20:00'::time, '22:30'::time, 240000, 'Gio vang buoi toi' from courts union all
select id, 'HOLIDAY'::day_type, '06:00'::time, '22:00'::time, 300000, 'Ngay le' from courts;

insert into court_services (court_id, name, description, price)
select id, 'Nuoc suoi', 'Chai 500ml', 10000 from courts union all
select id, 'Thue vot/bong', 'Dung cu co ban theo mon', 50000 from courts union all
select id, 'Trong tai', 'Ho tro dieu hanh tran dau', 150000 from courts;

insert into court_services (court_id, name, description, price)
select id, 'Ao bib', 'Ao phan doi cho bong da va bong ro', 30000 from courts union all
select id, 'Khan lanh', 'Khan lanh sau tran', 12000 from courts union all
select id, 'Nuoc dien giai', 'Chai 500ml', 18000 from courts union all
select id, 'Huan luyen vien', 'Dat lich huan luyen co ban theo gio', 250000 from courts;

insert into bookings (id, booking_code, user_id, court_id, booking_date, start_time, end_time, total_price, payment_method, payment_status, booking_status) values
('40000000-0000-0000-0000-000000000001','BK202606080001','00000000-0000-0000-0000-000000000021','30000000-0000-0000-0000-000000000001','2026-06-10','18:00','20:00',410000,'CASH','UNPAID','CONFIRMED'),
('40000000-0000-0000-0000-000000000002','BK202606080002','00000000-0000-0000-0000-000000000022','30000000-0000-0000-0000-000000000002','2026-06-09','07:00','08:30',230000,'E_WALLET','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000003','BK202606080003','00000000-0000-0000-0000-000000000023','30000000-0000-0000-0000-000000000006','2026-06-11','19:00','21:00',360000,'BANK_TRANSFER','PAID','PENDING');

insert into bookings (id, booking_code, user_id, court_id, booking_date, start_time, end_time, total_price, payment_method, payment_status, booking_status) values
('40000000-0000-0000-0000-000000000004','BK202606080004','00000000-0000-0000-0000-000000000021','30000000-0000-0000-0000-000000000001','2026-06-01','06:00','08:00',260000,'E_WALLET','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000005','BK202606080005','00000000-0000-0000-0000-000000000023','30000000-0000-0000-0000-000000000001','2026-06-02','18:00','20:00',410000,'BANK_TRANSFER','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000006','BK202606080006','00000000-0000-0000-0000-000000000024','30000000-0000-0000-0000-000000000003','2026-06-03','19:00','21:00',360000,'CASH','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000007','BK202606080007','00000000-0000-0000-0000-000000000025','30000000-0000-0000-0000-000000000004','2026-06-04','17:00','19:00',380000,'E_WALLET','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000008','BK202606080008','00000000-0000-0000-0000-000000000026','30000000-0000-0000-0000-000000000011','2026-06-05','18:00','20:00',520000,'BANK_TRANSFER','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000009','BK202606080009','00000000-0000-0000-0000-000000000027','30000000-0000-0000-0000-000000000011','2026-06-06','20:00','22:00',520000,'E_WALLET','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000010','BK202606080010','00000000-0000-0000-0000-000000000028','30000000-0000-0000-0000-000000000012','2026-06-07','07:00','09:00',220000,'CASH','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000011','BK202606080011','00000000-0000-0000-0000-000000000029','30000000-0000-0000-0000-000000000014','2026-06-08','18:00','20:00',450000,'MOCK_PAYMENT','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000012','BK202606080012','00000000-0000-0000-0000-000000000030','30000000-0000-0000-0000-000000000016','2026-06-09','19:00','21:00',420000,'E_WALLET','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000013','BK202606080013','00000000-0000-0000-0000-000000000031','30000000-0000-0000-0000-000000000018','2026-06-10','06:00','08:00',240000,'BANK_TRANSFER','PAID','COMPLETED'),
('40000000-0000-0000-0000-000000000014','BK202606080014','00000000-0000-0000-0000-000000000032','30000000-0000-0000-0000-000000000020','2026-06-10','18:00','20:00',420000,'CASH','UNPAID','CONFIRMED');

insert into booking_services (booking_id, service_id, quantity, price)
select '40000000-0000-0000-0000-000000000001'::uuid, id, 1, price from court_services where court_id = '30000000-0000-0000-0000-000000000001' and name = 'Nuoc suoi'
union all
select '40000000-0000-0000-0000-000000000002'::uuid, id, 1, price from court_services where court_id = '30000000-0000-0000-0000-000000000002' and name = 'Thue vot/bong';

insert into booking_services (booking_id, service_id, quantity, price)
select '40000000-0000-0000-0000-000000000004'::uuid, id, 2, price from court_services where court_id = '30000000-0000-0000-0000-000000000001' and name = 'Nuoc dien giai'
union all
select '40000000-0000-0000-0000-000000000005'::uuid, id, 1, price from court_services where court_id = '30000000-0000-0000-0000-000000000001' and name = 'Trong tai'
union all
select '40000000-0000-0000-0000-000000000008'::uuid, id, 1, price from court_services where court_id = '30000000-0000-0000-0000-000000000011' and name = 'Ao bib'
union all
select '40000000-0000-0000-0000-000000000010'::uuid, id, 1, price from court_services where court_id = '30000000-0000-0000-0000-000000000012' and name = 'Thue vot/bong'
union all
select '40000000-0000-0000-0000-000000000011'::uuid, id, 1, price from court_services where court_id = '30000000-0000-0000-0000-000000000014' and name = 'Nuoc suoi';

insert into reviews (user_id, court_id, booking_id, rating, comment, display_status) values
('00000000-0000-0000-0000-000000000022','30000000-0000-0000-0000-000000000002','40000000-0000-0000-0000-000000000002',5,'San sach, nhan vien ho tro nhanh.','VISIBLE');

insert into reviews (user_id, court_id, booking_id, rating, comment, display_status) values
('00000000-0000-0000-0000-000000000021','30000000-0000-0000-0000-000000000001','40000000-0000-0000-0000-000000000004',5,'Mat san em, den sang va khu gui xe rong.','VISIBLE'),
('00000000-0000-0000-0000-000000000023','30000000-0000-0000-0000-000000000001','40000000-0000-0000-0000-000000000005',4,'Dat lich nhanh, san dong vao gio toi nhung van on.','VISIBLE'),
('00000000-0000-0000-0000-000000000024','30000000-0000-0000-0000-000000000003','40000000-0000-0000-0000-000000000006',4,'San trong nha sach, nen bo sung them quat.','VISIBLE'),
('00000000-0000-0000-0000-000000000025','30000000-0000-0000-0000-000000000004','40000000-0000-0000-0000-000000000007',5,'Pickleball moi, vach san ro va nhan vien de thuong.','VISIBLE'),
('00000000-0000-0000-0000-000000000026','30000000-0000-0000-0000-000000000011','40000000-0000-0000-0000-000000000008',4,'Vi tri de tim, san bong phu hop da giao huu.','VISIBLE'),
('00000000-0000-0000-0000-000000000027','30000000-0000-0000-0000-000000000011','40000000-0000-0000-0000-000000000009',5,'San dep, anh tren web dung thuc te, se quay lai.','VISIBLE'),
('00000000-0000-0000-0000-000000000028','30000000-0000-0000-0000-000000000012','40000000-0000-0000-0000-000000000010',4,'Nhieu san cau long, dat khung gio kha tien.','VISIBLE'),
('00000000-0000-0000-0000-000000000029','30000000-0000-0000-0000-000000000014','40000000-0000-0000-0000-000000000011',5,'San bong ro trong nha rat on, anh em choi vui.','VISIBLE'),
('00000000-0000-0000-0000-000000000030','30000000-0000-0000-0000-000000000016','40000000-0000-0000-0000-000000000012',5,'San pickleball moi va thoang, co the dat lai cuoi tuan.','VISIBLE'),
('00000000-0000-0000-0000-000000000031','30000000-0000-0000-0000-000000000018','40000000-0000-0000-0000-000000000013',4,'Gia hop ly, san sang som con trong nhieu.','VISIBLE');

insert into reports (user_id, court_id, reason, description, status) values
('00000000-0000-0000-0000-000000000024','30000000-0000-0000-0000-000000000003','Thong tin chua cap nhat','So dien thoai lien he khong dung.','PENDING');

insert into reports (user_id, court_id, reason, description, status) values
('00000000-0000-0000-0000-000000000021','30000000-0000-0000-0000-000000000001','Gia hien thi chua dung','Gia gio vang ngoai san cao hon tren web.','PENDING'),
('00000000-0000-0000-0000-000000000022','30000000-0000-0000-0000-000000000002','Anh san can cap nhat','Anh dai dien hoi cu so voi hien tai.','RESOLVED'),
('00000000-0000-0000-0000-000000000023','30000000-0000-0000-0000-000000000006','Khung gio trung lich','Khung 19:00 da co doi khac nhung app van cho dat.','PENDING'),
('00000000-0000-0000-0000-000000000025','30000000-0000-0000-0000-000000000004','Dich vu phu thu','Nuoc uong phu thu chua hien ro.','RESOLVED'),
('00000000-0000-0000-0000-000000000026','30000000-0000-0000-0000-000000000011','Dia chi kho tim','Can bo sung huong dan vao san chi tiet hon.','PENDING'),
('00000000-0000-0000-0000-000000000027','30000000-0000-0000-0000-000000000012','Nhan vien ho tro cham','Can lien he xac nhan nhanh hon.','REJECTED'),
('00000000-0000-0000-0000-000000000028','30000000-0000-0000-0000-000000000014','Thieu thong tin tien ich','Chua thay thong tin phong thay do.','PENDING'),
('00000000-0000-0000-0000-000000000029','30000000-0000-0000-0000-000000000016','Loi thanh toan','Thanh toan thanh cong nhung trang thai cap nhat cham.','RESOLVED'),
('00000000-0000-0000-0000-000000000030','30000000-0000-0000-0000-000000000018','Can them anh san','Gallery hien con it anh.','PENDING'),
('00000000-0000-0000-0000-000000000031','30000000-0000-0000-0000-000000000020','Khung gio khong kha dung','Mot so gio da khoa nhung khong co ghi chu.','PENDING');

insert into notifications (user_id, title, content, type) values
('00000000-0000-0000-0000-000000000021','Dat san thanh cong','Don BK202606080001 dang cho san xac nhan.','BOOKING'),
('00000000-0000-0000-0000-000000000011','Co don dat san moi','San bong Sala 1 co don dat san moi.','PARTNER_BOOKING');

insert into notifications (user_id, title, content, type) values
('00000000-0000-0000-0000-000000000021','Lich dat sap dien ra','Ban co lich San bong Sala 1 vao 18:00 ngay 10/06.','BOOKING_REMINDER'),
('00000000-0000-0000-0000-000000000022','Cam on danh gia','Danh gia cua ban da duoc ghi nhan.','REVIEW'),
('00000000-0000-0000-0000-000000000023','Don dat san dang cho xac nhan','Don BK202606080003 dang cho doi tac xac nhan.','BOOKING'),
('00000000-0000-0000-0000-000000000026','Thanh toan thanh cong','Don BK202606080008 da thanh toan thanh cong.','PAYMENT'),
('00000000-0000-0000-0000-000000000027','Danh gia thanh cong','Cam on ban da danh gia San bong The One Gamuda.','REVIEW'),
('00000000-0000-0000-0000-000000000011','Can xu ly bao cao','Co bao cao moi lien quan den San bong Sala 1.','REPORT'),
('00000000-0000-0000-0000-000000000013','Co don dat san moi','San bong The One Gamuda co lich dat moi.','PARTNER_BOOKING'),
('00000000-0000-0000-0000-000000000014','Bao cao doanh thu','Doanh thu hom nay da duoc cap nhat.','PARTNER_REVENUE'),
('00000000-0000-0000-0000-000000000015','Can cap nhat san','Hay bo sung them anh cho Cau long Mekong Hall.','PARTNER_PROFILE'),
('00000000-0000-0000-0000-000000000001','Co san cho duyet','He thong co san moi can admin xem xet.','ADMIN_TASK');
