import { useState } from "react";
import { keepPreviousData, useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { adminApi } from "../../features/admin/api/adminApi";
import { useAuth } from "../../features/auth/hooks/useAuth";
import { Button } from "../../components/ui/Button";import { Input } from "../../components/ui/Input";import { Select } from "../../components/ui/Select";import { ErrorState,LoadingState } from "../../components/common/States";import { SortableTh } from "../../components/common/SortableTh";import { useUrlSort } from "../../hooks/useUrlSort";
type SortField="fullName"|"email"|"role"|"status";
const SORT_FIELDS:SortField[]=["fullName","email","role","status"];
export function AdminUsersPage(){const {user:me}=useAuth();const qc=useQueryClient();const[page,setPage]=useState(1);const[f,setF]=useState({search:"",role:"",status:""});const {sortField,sortOrder,handleSort:sortBy}=useUrlSort<SortField>({fields:SORT_FIELDS,default:null});const handleSort=(field:SortField)=>{setPage(1);sortBy(field)};const users=useQuery({queryKey:["admin-users",page,f,sortField,sortOrder],queryFn:()=>adminApi.users({page,limit:10,...f,sortBy:sortField??undefined,sortOrder}),placeholderData:keepPreviousData});const toggle=useMutation({mutationFn:({id,status}:{id:string;status:string})=>status==="ACTIVE"?adminApi.lockUser(id):adminApi.unlockUser(id),onSuccess:async()=>{toast.success("Đã cập nhật tài khoản");await qc.invalidateQueries({queryKey:["admin-users"]})},onError:e=>toast.error(e.message)});if(users.isLoading)return <LoadingState/>;if(users.isError)return <ErrorState message={users.error.message}/>;return <div className="space-y-5"><h1 className="text-3xl font-bold">Người dùng</h1><div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3"><Input label="Tìm kiếm" value={f.search} onChange={e=>{setPage(1);setF({...f,search:e.target.value})}}/><Select label="Vai trò" value={f.role} onChange={e=>setF({...f,role:e.target.value})} options={[{value:"",label:"Tất cả"},...["USER","PARTNER","ADMIN"].map(x=>({value:x,label:x}))]}/><Select label="Trạng thái" value={f.status} onChange={e=>setF({...f,status:e.target.value})} options={[{value:"",label:"Tất cả"},{value:"ACTIVE",label:"ACTIVE"},{value:"LOCKED",label:"LOCKED"}]}/></div><div className="overflow-auto rounded-2xl border bg-white"><table className="w-full min-w-[800px] text-sm"><thead><tr className="bg-slate-50 text-left"><SortableTh className="p-3" label="Họ tên" field="fullName" sortField={sortField} sortOrder={sortOrder} onSort={handleSort}/><SortableTh label="Email" field="email" sortField={sortField} sortOrder={sortOrder} onSort={handleSort}/><SortableTh label="Vai trò" field="role" sortField={sortField} sortOrder={sortOrder} onSort={handleSort}/><SortableTh label="Trạng thái" field="status" sortField={sortField} sortOrder={sortOrder} onSort={handleSort}/><th></th></tr></thead><tbody>{users.data?.items.map(u=><tr key={u.id} className="border-t"><td className="p-3">{u.fullName}</td><td>{u.email}</td><td>{u.role}</td><td>{u.status}</td><td className="text-right"><Button variant={u.status==="ACTIVE"?"danger":"secondary"} disabled={u.id===me?.id||toggle.isPending} onClick={()=>toggle.mutate({id:u.id,status:u.status})}>{u.id===me?.id?"Tài khoản hiện tại":u.status==="ACTIVE"?"Khóa":"Mở khóa"}</Button></td></tr>)}</tbody></table></div><Pager page={page} total={users.data?.meta.totalPages??1} setPage={setPage}/></div>}
function Pager({page,total,setPage}:{page:number;total:number;setPage:(v:number)=>void}){return <div className="flex justify-end gap-3"><Button variant="secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Trước</Button><span className="py-2">{page}/{Math.max(total,1)}</span><Button variant="secondary" disabled={page>=total} onClick={()=>setPage(page+1)}>Sau</Button></div>}
