export type CourtListQuery = {
  page?: string;
  limit?: string;
  q?: string;
  keyword?: string;
  sportType?: string;
  province?: string;
  city?: string;
  district?: string;
  latitude?: string;
  longitude?: string;
  radiusKm?: string;
  date?: string;
  startTime?: string;
  endTime?: string;
  minPrice?: string;
  maxPrice?: string;
  rating?: string;
  categoryId?: string;
  sortBy?: string;
  sortOrder?: "asc" | "desc";
  sort?: "newest" | "price_asc" | "price_desc";
};
